line_length: 140
force_cast: error
excluded:
    - .build
disabled_rules: # Because they mess up with sourcery
    - cyclomatic_complexity # Composable
    - function_body_length # Composable
    - nesting # CodingKeys in Parten.Child props